name: Create New GKE Cluster
description: Request a new GKE cluster
title: "[Create] "
labels: ["cluster-create", "pending-approval"]

body:
  - type: markdown
    attributes:
      value: |
        ## New Cluster Request
        
        > **Note:** After submitting, a Platform team member will review 
        > and add the `approved` label to begin provisioning.

  # ===========================
  # CHANGE MANAGEMENT
  # ===========================
  - type: input
    id: change_ticket
    attributes:
      label: Change Ticket Number
      description: ServiceNow/Jira change ticket number
      placeholder: "CHG0012345 or JIRA-1234"
    validations:
      required: true

  # ===========================
  # PROJECT INFO
  # ===========================

  - type: input
    id: gcp_project_id
    attributes:
      label: GCP Project ID
      description: The Google Cloud project where cluster will be created
      placeholder: "my-project-id"
    validations:
      required: true

  # ===========================
  # NETWORKING
  # ===========================

  - type: markdown
    attributes:
      value: |
        ## Networking

  - type: input
    id: vpc_name
    attributes:
      label: VPC Network Name
      description: Name of the VPC network (leave empty for "default")
      placeholder: "my-custom-vpc"
    validations:
      required: false

  - type: input
    id: subnet_name
    attributes:
      label: Subnet Name
      description: Name of the subnet (leave empty for "default")
      placeholder: "my-subnet"
    validations:
      required: false   

  # ===========================
  # BASIC INFO
  # ===========================

  - type: input
    id: cluster_name
    attributes:
      label: Cluster Name
      description: Unique name (lowercase, hyphens only)
      placeholder: "my-team-dev (lowercase, letters, numbers, hyphens only)"
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - dev
        - staging
        - prod
    validations:
      required: true

  - type: dropdown
    id: zone
    attributes:
      label: GCP Zone
      options:
        - us-central1-a
        - us-central1-b
        - us-east1-b
        - us-west1-a
    validations:
      required: true

  # ===========================
  # NODE CONFIGURATION
  # ===========================

  - type: markdown
    attributes:
      value: |
        ## Node Configuration

  - type: dropdown
    id: machine_type
    attributes:
      label: Machine Type
      options:
        - e2-small
        - e2-medium
        - e2-standard-2
        - e2-standard-4
    validations:
      required: true

  - type: dropdown
    id: disk_size
    attributes:
      label: Disk Size (GB)
      options:
        - "30"
        - "50"
        - "100"
    validations:
      required: true

  # ===========================
  # AUTOSCALING
  # ===========================

  - type: markdown
    attributes:
      value: |
        ## Autoscaling Configuration

  - type: dropdown
    id: enable_autoscaling
    attributes:
      label: Enable Autoscaling?
      description: Automatically adjust the number of nodes based on workload
      options:
        - "no"
        - "yes"
    validations:
      required: true

  - type: dropdown
    id: node_count
    attributes:
      label: Number of Nodes (if autoscaling disabled)
      description: Fixed node count when autoscaling is OFF
      options:
        - "1"
        - "2"
        - "3"
    validations:
      required: true

  - type: dropdown
    id: min_nodes
    attributes:
      label: Minimum Nodes (if autoscaling enabled)
      description: Minimum number of nodes to keep running
      options:
        - "1"
        - "2"
        - "3"
    validations:
      required: true

  - type: dropdown
    id: max_nodes
    attributes:
      label: Maximum Nodes (if autoscaling enabled)
      description: Maximum number of nodes to scale up to
      options:
        - "3"
        - "5"
        - "10"
        - "15"
    validations:
      required: true

  # ===========================
  # COST OPTIMIZATION
  # ===========================

  - type: markdown
    attributes:
      value: |
        ## Cost Optimization

  - type: dropdown
    id: use_spot_vms
    attributes:
      label: Use Spot VMs?
      description: Up to 90% cost savings, but VMs can be preempted (good for dev/staging)
      options:
        - "no"
        - "yes"
    validations:
      required: true

  # ===========================
  # OWNERSHIP
  # ===========================

  - type: markdown
    attributes:
      value: |
        ## Ownership

  - type: input
    id: team
    attributes:
      label: Team Name
      placeholder: "platform"
    validations:
      required: true

  - type: input
    id: owner_email
    attributes:
      label: Owner Email
      placeholder: "you@example.com"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      placeholder: "Why do you need this cluster? What workloads will run on it?"
    validations:
      required: true